In [1]:
import numpy as np

1. Примеры создания массивов

Из обычных списков

In [17]:
arr_list = np.array([1, 2, 3, 4, 5])
arr_list

array([1, 2, 3, 4, 5])

Использование zeros, ones, arange

In [18]:
arr_zeros = np.zeros(5)
arr_ones = np.ones(5)
arr_arange = np.arange(0, 10, 2)

arr_zeros, arr_ones, arr_arange

(array([0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]),
 array([0, 2, 4, 6, 8]))

Демонстрация атрибутов shape и dtype

In [20]:
print("Форма массива:", arr_arange.shape)
print("Тип данных:", arr_arange.dtype)

Форма массива: (5,)
Тип данных: int64


2.Индексация и срезы

Получение отдельного элемента

In [22]:
element = arr_list[2]   # элемент с индексом 2
element

np.int64(3)

Извлечение подмассива с помощью среза

In [24]:
sub_array = arr_list[1:4]  # элементы со 2-го по 4-й
sub_array

array([2, 3, 4])

3. Векторные операции и базовая статистика

Сложение двух массивов

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a_plus_b = a + b
a_plus_b

array([5, 7, 9])

Умножение двух массивов

In [27]:
a_times_b = a * b
a_times_b

array([ 4, 10, 18])

Среднее значение

In [28]:
mean_value = np.mean(a)
mean_value

np.float64(2.0)